### ISSUE TITLE
Service Fabrik OOB backup scheduler does not show proper backup type

### ISSUE THREAD

**Issue by sauravmndl** [SAP/service-fabrik-broker#23]
Trigger an ondemand backup using and when listing and the backup type shows as 'scheduled'.

**Comment by akskap** [comment]
**Description**

When an ondemand backup is triggered, meta information of the backup does not differentiate between 'ondemand' and 'scheduled' which might confuse the user

**Steps to reproduce the issue:**

1) Initiate an ondemand backup for a service-instance using './broker oob-backup-start <deployment_name>'
2) Checking the status of the backup of service-instance using ' ./broker oob-backup-show-all <deployment_name>' shows backup type as 'sheduled'

**Output Received:**

Backup type shows as 'scheduled'

**Output Expected**

Backup type should show as 'ondemand'

**Output of `bosh -v`:**
```
version 2.0.29-1f8ec43-2017-07-14T16:10:28Z
```

**Environment Details**

AWS

**Comment by subhankarc** [comment]
@sauravmndl Is this fixed already? Please close if so.
