### ISSUE TITLE
BackupReaper Job audit log on deletions are erroring

### ISSUE THREAD

**Issue by jagadish-kb** [SAP/service-fabrik-broker#49]
Backup reaper job audit logs are erroring as EventLoginterceptor is unable to find the event config files. Currently event config files are only part of service-fabrik-broker job and they are not part of scheduler. As part of this fix, need to ensure we have the event config even in scheduler.

**Comment by kamath-prasad** [comment]
Fixed here - https://github.com/SAP/service-fabrik-boshrelease/pull/16
