### ISSUE TITLE
Wrong quota calculation for similar plan names

### ISSUE THREAD

**Issue by subhankarc** [SAP/service-fabrik-broker#61]
**Description**

Plans with name like v1.0-xsmall and v1.0small are treated as same SKU. Also, v1.0-dev-large and v1.0-large are treated as same SKU

**Steps to reproduce the issue:**
1. Keep quota of v1.0-xsmall as 1 and v1.0-small as 1
2. Create one v1.0-xsmall instance.
3. Now try to create one v1.0-small, it gives quota exceeded.

**If you are running service fabrik locally than Output of `node -v 
for node version and grep version package.json for service fabrik version`:**

```
(paste your output here)
node version: v7.1.0
service fabrik: 3.0.1
```

**Additional environment details (AWS, VirtualBox, OpenStack, etc.):**

**Comment by kamath-prasad** [comment]
Issue fixed and delivered.
