### ISSUE TITLE
Why rewrite cf-containers-broker?

### ISSUE THREAD

**Issue by drnic** [SAP/service-fabrik-broker#65]
Towards understanding what future cf-containers-broker might have, why was service-fabrik-broker a rewrite of cf-containers-broker; and what features have been added to service-fabrik that weren't in cf-containers-broker? Could those features have been added to ccb? Should ccb project be shut down?

**Comment by ashishjain14** [comment]
We wanted a broker implementation which could help us with provisioning of container as well as BOSH based service instances. Moreover most of our internal implementations use nodejs as a runtime hence we choose to move from ruby to nodejs.

**Comment by drnic** [comment]
It’s obviously too late to discuss it now as you’ve done the work. cf-containers-broker already had an abstraction for alternate provisioning systems. `docker_manager.rb` was just one implementation.
